// src/constants/errors.ts
export const ERROR_CODES = {
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  NO_ACTIVE_CARD: "NO_ACTIVE_CARD",
  INVALID_INDEX: "INVALID_INDEX",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  GAME_NOT_STARTED: "GAME_NOT_STARTED",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  SERVER_ERROR: "SERVER_ERROR",
  NO_MORE_CARDS: "NO_MORE_CARDS",
  ACTION_IN_PROGRESS: "ACTION_IN_PROGRESS",
} as const;


export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];